### ISSUE TITLE
Fixing documentation

### ISSUE THREAD

**Issue by sowmya-hub** [absotone/spotifynd-docs#1]
Typo in the **Get your spotify API credentials** section of the readme file

**Comment by vijay-jaisankar** [comment]
Hi @sowmya-hub, thanks for raising the issue! 

Please feel free to make a PR

**Comment by sowmya-hub** [comment]
Hi @vijay-jaisankar, thanks for assigning me the issue :)

I'll submit a PR soon!

**Comment by sowmya-hub** [comment]
Hey, I seem to be having an issue with my remote access permission to the repo which is preventing me from pushing the changes to my PR. 
I'm working on it, and will get it done ASAP.

**Comment by vijay-jaisankar** [comment]
Hey @sowmya-hub, no problem, take your time!

Also, the remote access permission could be because of HTTPS based authentication, which is now deprecated. 
Ref: https://docs.github.com/en/authentication/connecting-to-github-with-ssh

**Comment by sowmya-hub** [comment]
Oh, I did not know that. Thank you for providing the link! 

I'll read up on it and retry pushing the changes :D

**Comment by vijay-jaisankar** [comment]
Hi @sowmya-hub, just wanted to confirm if you'd still like to work on this.

**Comment by sowmya-hub** [comment]
Hi @vijay-jaisankar. Yes, I'd like to, really sorry that I haven't gotten around to it yet.

**Comment by vijay-jaisankar** [comment]
Closed as completed via #2
